@startuml
class Usuario {
    -CPF: String
    -nome: String
    -DDD: String
    -telefoneCelular: String
    -email: String
}

class DEEC {
    +informarNome()
    +informarDescricao()
    +visualizarCadastros()
    +informarQuantidadeDeHoras()
    +removerDemanda()
    +importarPlanilha()
    +validarEntrega(aluno: Aluno)
    +encaminharComprovanteDeEntrega(comprovante: ComprovanteDeEntrega)
}

class Aluno {
    -curso: String
    -projeto: String
    -atividadeDesenvolvida: String
    -programa: String
    -tipo: String
    -concluiuHoras: boolean
    -vinculacaoSetorBolsas: boolean
    -declaracaoEnviada: boolean
    +visualizarDemandas()
    +selecionarDemanda(demanda: Demanda)
    +trocarDemanda(demanda: Demanda)
    +efetivarPresenca(demanda: Demanda)
    +efetivarEntrega(demanda: Demanda)
}

class Demanda {
    -nome: String
    -descricao: String
    -quantidadeDeHoras: int
    -quantidadeDeVagas: int
}

class ComprovanteDeEntrega {
    -pdfFile: File
    +gerarPDF()
}

Usuario <|-- DEEC
Usuario <|-- Aluno

DEEC "1" -- "0..*" Demanda: gerenciar
DEEC "1" -- "1" ComprovanteDeEntrega: encaminhar

ResponsavelDemanda "1" -- "1" Demanda: responsavel
ResponsavelDemanda "1..*" -- "*" Aluno
@enduml